DROP DATABASE IF EXISTS python;
REVOKE ALL PRIVILEGES ON DATABASE postgres FROM python;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM python;
REASSIGN OWNED BY python TO postgres;
DROP OWNED BY python;
DROP USER IF EXISTS python;
