# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(600, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/white/login.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        Login.setWindowIcon(icon)
        Login.setStyleSheet("QWidget{\n"
"    background-color: #202020;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-top: none;\n"
"    border-bottom: 2px solid #a2a6aebc;\n"
"    /*border-radius: 25px;*/\n"
"    color: #fff;\n"
"    font-size: 12pt;\n"
"    padding-left: 5px;\n"
"}\n"
"\n"
"QLineEdit:Focus{\n"
"    border-bottom: 2px solid #ffffff;\n"
"}\n"
"\n"
"#LoginBtn{\n"
"    border: 2px solid #a2a6aebc;\n"
"    border-radius: 25px;\n"
"    color: #fff;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"#LoginBtn:Hover{\n"
"    background-color: #fff;\n"
"    color: #000;\n"
"}\n"
"\n"
"#Profile{\n"
"    border-radius: 50px;\n"
"}")
        self.Username = QtWidgets.QLineEdit(parent=Login)
        self.Username.setGeometry(QtCore.QRect(110, 280, 391, 51))
        self.Username.setStyleSheet("")
        self.Username.setObjectName("Username")
        self.Password = QtWidgets.QLineEdit(parent=Login)
        self.Password.setGeometry(QtCore.QRect(110, 350, 391, 51))
        self.Password.setStyleSheet("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Password.setObjectName("Password")
        self.LoginBtn = QtWidgets.QPushButton(parent=Login)
        self.LoginBtn.setGeometry(QtCore.QRect(110, 460, 391, 51))
        self.LoginBtn.setObjectName("LoginBtn")
        self.frame = QtWidgets.QFrame(parent=Login)
        self.frame.setGeometry(QtCore.QRect(200, 50, 201, 181))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Profile = QtWidgets.QPushButton(parent=self.frame)
        self.Profile.setGeometry(QtCore.QRect(0, 0, 201, 181))
        self.Profile.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/white/login.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Profile.setIcon(icon1)
        self.Profile.setIconSize(QtCore.QSize(150, 150))
        self.Profile.setObjectName("Profile")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", " Admin Login"))
        self.Username.setPlaceholderText(_translate("Login", " Username"))
        self.Password.setPlaceholderText(_translate("Login", " Password"))
        self.LoginBtn.setText(_translate("Login", "LOGIN"))

if __name__=='__main__':
    app = QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec())
