CREATE DATABASE python;
CREATE USER python WITH PASSWORD 'python';
GRANT ALL PRIVILEGES ON SCHEMA public TO python;
ALTER DATABASE python OWNER TO python;
GRANT ALL PRIVILEGES ON DATABASE python TO python;
