CREATE TABLE IF NOT EXISTS APP_USER (
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS APP_STUDENT (
  cursus TEXT NOT NULL UNIQUE,
  class TEXT NOT NULL
) INHERITS (APP_USER);
