# grade table controller file
# autogenerated by filegenerator.py

from sys import path
from os.path import abspath as abs, join as jn, dirname as dir
path.append(abs(jn(dir(__file__), '..', '..')))

from classes.database.dbcrud import CrudHandler as handle_crud

grade = handle_crud('grade')

grade_data_template = {
    'theorical_grade': 'theorical_grade',
    'pratical_grade': 'pratical_grade',
    'fk_cename': 'fk_cename',
    'fk_student_id': 'fk_student_id',
    'fk_teacher_id': 'fk_teacher_id',
    'PRIMARY': 'PRIMARY',
    'fk_teacher_id': 'fk_teacher_id',
    'fk_student_id)': 'fk_student_id)'
}

grade_new_data_template = {
    'theorical_grade': 'new_theorical_grade',
    'pratical_grade': 'new_pratical_grade',
    'fk_cename': 'new_fk_cename',
    'fk_student_id': 'new_fk_student_id',
    'fk_teacher_id': 'new_fk_teacher_id',
    'PRIMARY': 'new_PRIMARY',
    'fk_teacher_id': 'new_fk_teacher_id',
    'fk_student_id)': 'new_fk_student_id)'
}

def grade_insert_template():
    return grade.insert(grade_data_template)

def grade_insert(grade_data):
    return grade.insert(grade_data)

def grade_select_all():
    return grade.select_all()

def grade_count():
    return grade.count()

def grade_select(grade_data):
    return grade.select(grade_data)

def grade_update(grade_data, grade_new_data):
    return grade.update(grade_data, grade_new_data)

def grade_delete(grade_data):
    return grade.delete(grade_data)

def grade_delete_all():
    return grade.delete_all()

if __name__ == '__main__':
    print("insert template")
    grade_insert_template()
    print(grade_select_all())
    print(" ")

    print("select grade_data")
    print(grade_select(grade_data_template))
    print(" ")

    print("update grade_data")
    grade_update(
        grade_data_template,
        grade_new_data_template
    )
    print(grade_select_all())
    print(" ")

    print("insert grade_data")
    grade_insert(grade_data_template)
    print(grade_select_all())
    print(" ")

    print("Counting grade")
    print(f"Number of grade : {grade_count()}")
    print(" ")

    print("delete grade_data")
    grade_delete(grade_data_template)
    print(grade_select_all())
    print(" ")

    print("delete all")
    grade_delete_all()
    print(grade_select_all())
